
[ClassVersion("1.0.0.0"), FriendlyName("xUnitySetupInstance")]
class xUnitySetupInstance : OMI_BaseResource
{
    [Key, Description("Comma separated list of Unity versions. ")] string Versions;
    [Write, Description("Ensure present or absent?"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("What components to ensure are present?")] string Components[];
};

